DROP TABLE IF EXISTS rates CASCADE;

CREATE TABLE rates  (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL default 0
);
